config/routes.rb
Rails.application.routes.draw do

  # Set Root Path
  root 'components#forms'

  # Routes for Components
  get 'components/active_record_associations' => 'components#active_record_associations'
  get 'components/active_record_migrations' => 'components#active_record_migrations'
  get 'components/forms' => 'components#forms'
  get 'components/images' => 'components#images'
  get 'components/links' => 'components#links'

  # Routes for How-To's
  get 'how_to/create_a_new_rails_app' => 'how_to#create_a_new_rails_app'
  get 'how_to/skeleton_app' => 'how_to#skeleton_app'
  get 'how_to/setup_bootstrap' => 'how_to#setup_bootstrap'

  # Routes for Build App Tutorials
  get 'tutorials/build_a_blog_app' => 'tutorials#build_a_blog_app'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  def active_record_associations
  end

  def active_record_migrations
  end

  def forms
  end

  def images
  end

  def links
  end
end

app/controllers/how_to_controller.rb
class HowToController < ApplicationController
  before_action :set_list_of_actions

  def create_a_new_rails_app
  end

  def skeleton_app
    @page_title = 'How to: Create a Rails App'
    @page_subtitle = ''
  end

  def setup_bootstrap
    @page_title = 'How to Setup Bootstrap in Rails'
    @page_subtitle = ''
  end

  def forms
    @page_title = 'Forms'
    @page_subtitle = ''
  end

  private

  def set_list_of_actions
    @list_of_actions = TutorialsController.action_methods
  end

end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_list_of_actions

  def build_a_blog_app
  end

  private

  def set_list_of_actions
    @list_of_actions = TutorialsController.action_methods
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(name = nil, options = nil, html_options = nil, &block)
    active_class = html_options[:active] || "active"
    html_options.delete(:active)
    html_options[:class] = "#{html_options[:class]} #{active_class}" if current_page?(options)
    link_to(name, options, html_options, &block)
  end
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/how_to_helper.rb
module HowToHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/how_to/create_a_blog.html.erb
<article>
  <h3 class="mt-5">Create Multiple Pages</h3>
  <p class="w-75">Type in Terminal...</p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">TERMINAL</span>
$ rails g controller pages home product pricing

</code></pre>

<p class="w-75">It should have generated <code>app/controllers/pages_controller.rb</code> with the 3 'actions' we specified.</p>
<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">CODE EDITOR</span>
<span class="block">class</span> PagesController < ApplicationController
  <span class="block">def</span> home
  <span class="block">end</span>

  <span class="block">def</span> product
  <span class="block">end</span>

  <span class="block">def</span> pricing
  <span class="block">end</span>
<span class="block">end</span>

</code></pre>

<p class="w-75">It should have also generated their corresponding 'view', or pages.
  Notice that the pages match the action names and the folder matches the controller name.
  This is done on purpose because Rails automatically associates them.</p>
<ul>
  <li><code>app/views/pages/home.html.erb</code></li>
  <li><code>app/views/pages/product.html.erb</code></li>
  <li><code>app/views/pages/pricing.html.erb</code></li>
</ul>
</article>


<article>
  <h3 class="mt-5">Set a Home Page</h3>
  <p class="w-75">Open and edit <code>config/routes.rb</code></p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">CODE EDITOR</span>
Rails.application.routes.draw <span class="block">do</span>

  <span class="comment"># Set Root Path</span>
  <span class="method">root</span> 'pages#home'

<span class="block">end</span>

</code></pre>
<p class="w-75">This tells Rails that it can find the root page by going to the
  <code>PagesController</code> and the <code>home</code> action,
  which we know directs Rails to <code>pages/home.html.erb</code></p>
</article>


<article>
  <h3 class="mt-5">Add Bootstrap</h3>
  <p>Go to the <a href="https://getbootstrap.com/docs/4.4/getting-started/introduction/">Bootstrap website</a>
    to get their tags. The simplest way to add Bootstrap is to
    open <code>app/layouts/application.html.erb</code> and add the Bootstrap links,
    like you would with a normal HTML page.</p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">CODE EDITOR</span>
<span class="block">&lt;!DOCTYPE html&gt;</span>
<span class="block">&lt;html&gt;</span>
  <span class="block">&lt;head&gt;</span>
    <span class="block">&lt;title&gt;</span>Rails Genius<span class="block">&lt;/title&gt;</span>
    <span class="block">&lt;meta</span> charset="UTF-8"<span class="block">/&gt;</span>
    <span class="block">&lt;meta</span> name="viewport" content="width=device-width, initial-scale=1.0"<span class="block">/&gt;</span>
    <span class="block">&lt;%=</span> csrf_meta_tags <span class="block">%&gt;</span>
    <span class="block">&lt;%=</span> csp_meta_tag <span class="block">%&gt;</span>

    <span class="comment">&lt;!-- COPY PASTE BOOTSTRAP LINKS HERE --&gt;</span>
    <span class="block">&lt;link</span> rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"<span class="block">/&gt;</span>
    <span class="block">&lt;script</span> src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"&gt;<span class="block">&lt;/script&gt;</span>
    <span class="block">&lt;script</span> src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"&gt;<span class="block">&lt;/script&gt;</span>
    <span class="block">&lt;script</span> src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"&gt;<span class="block">&lt;/script&gt;</span>
    <span class="comment">&lt;!-- END --&gt;</span>

    <span class="block">&lt;%=</span> stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' <span class="block">%&gt;</span>
    <span class="block">&lt;%=</span> javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' <span class="block">%&gt;</span>
  <span class="block">&lt;/head&gt;</span>

  <span class="block">&lt;body&gt;</span>
    <span class="block">&lt;%=</span> yield <span class="block">%&gt;</span>
  <span class="block">&lt;/body&gt;</span>
<span class="block">&lt;/html&gt;</span>
</code></pre>
</article>


<article>
  <h3 class="mt-5">Use Bootstrap Templates</h3>
  <p class="w-75">We are going to use this
    <a href="https://getbootstrap.com/docs/4.4/examples/cover/">Bootstrap Cover Page Template.</a>
    Copy the all the HTML code between the <code>&lt;body&gt;</code> tag and
    paste it in <code>app/views/pages/home.html.erb</code></p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">CODE EDITOR</span>
&lt;div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column"&gt;
  &lt;header class="masthead mb-auto"&gt;
    &lt;div class="inner"&gt;
      &lt;h3 class="masthead-brand"&gt;Cover&lt;/h3&gt;
      &lt;nav class="nav nav-masthead justify-content-center"&gt;
        &lt;a class="nav-link active" href="#"&gt;Home&lt;/a&gt;
        &lt;a class="nav-link" href="#"&gt;Features&lt;/a&gt;
        &lt;a class="nav-link" href="#"&gt;Contact&lt;/a&gt;
      &lt;/nav&gt;
    &lt;/div&gt;
  &lt;/header&gt;

  &lt;main role="main" class="inner cover"&gt;
    &lt;h1 class="cover-heading"&gt;Cover your page.&lt;/h1&gt;
    &lt;p class="lead"&gt;Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.&lt;/p&gt;
    &lt;p class="lead"&gt;
      &lt;a href="#" class="btn btn-lg btn-secondary"&gt;Learn more&lt;/a&gt;
    &lt;/p&gt;
  &lt;/main&gt;

  &lt;footer class="mastfoot mt-auto"&gt;
    &lt;div class="inner"&gt;
      &lt;p&gt;Cover template for &lt;a href="https://getbootstrap.com/"&gt;Bootstrap&lt;/a&gt;, by &lt;a href="https://twitter.com/mdo"&gt;@mdo&lt;/a&gt;.&lt;/p&gt;
    &lt;/div&gt;
  &lt;/footer&gt;
&lt;/div&gt;

</code></pre>
<p class="w-75">You will need to do the same for our other two pages.</p>

<ul>
  <li><a href="https://getbootstrap.com/docs/4.4/examples/product/">Bootstrap Product Page Template</a></li>
  <li><a href="https://getbootstrap.com/docs/4.4/examples/pricing/">Bootstrap Pricing Page Template</a></li>
</ul>

<!-- Image trigger modal -->
<%= image_tag("use-bootstrap-templates.jpg", class: "img-fluid p-3 shadow", :data => { :target => "#useBootstrapTemplateModal", toggle: "modal" }) %>

<!-- Modal -->
<div class="modal fade" id="useBootstrapTemplateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Use Bootstrap Template</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag("use-bootstrap-templates.jpg", class: "img-fluid") %>
      </div>
    </div>
  </div>
</div>

</article>


<article>
  <h3 class="mt-5">Add the Bootstrap Template's CSS</h3>
  <p class="w-75">The styles are still not quite right because we are missing a CSS file that the templates use.
    If you inspect the <code>&lt;body&gt;</code> tag of the Cover Template, you should see a <code>cover.css</code>.
    Copy the CSS file and paste it in <code>app/stylesheets/cover.scss</code>. Rails will include it automatically.

<p class="w-75">You will need to do the same for the other two pages.</p>

</article>


<article>
  <h3 class="mt-5">Customize Links and URL's</h3>
  <p class="w-75">Open and edit <code>config/routes.rb</code></p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">CODE EDITOR</span>
Rails.application.routes.draw <span class="block">do</span>

  <span class="comment"># Set Root Path</span>
  <span class="method">root</span> 'pages#home'

  <span class="comment"># Set Custom URL for Pages </span>
  <span class="method">get</span> 'product' => 'pages#product'
  <span class="method">get</span> 'long/useless/deep/link/pricing' => 'pages#pricing'

<span class="block">end</span>

</code></pre>
<p>By default, the product page URL will be <code>http://localhost:3000/pages/product</code>,
  matching the Controller and Action name.</p>
<ul>
  <li><code>http://localhost:3000/product</code> will now show <code>app/views/pages/product.html.erb</code></li>
  <li><code>http://localhost:3000/long/useless/deep/link/pricing</code> will now show <code>app/views/pages/pricing.html.erb</code></li>
</ul>
</article>

app/views/how_to/create_a_new_rails_app.html.erb
<%= render 'layouts/partials/section_main_article_start' %>

  <h1 class="mt-5">How to Create a New Rails App</h1>
  <p class="w-75">This article will show how to create a new rails app.</p>

  <%= render 'how_to/partials/create_a_new_rails_app/rails_new' %>

  <%= render 'how_to/partials/create_a_new_rails_app/yay_youre_on_rails' %>

</section>

app/views/how_to/partials/_build_a_rails_app.html.erb
<article>
  <h3 class="mt-5">Create a Rails App</h3>
  <p class="w-75">Open terminal and navigate to the folder where you want to create the app.</p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">TERMINAL</span>
$ rails new my_new_app      <span class="comment"># creates an app named 'my_new_app'</span>
...

$ cd my_new_app             <span class="comment"># navigate in to the app folder</span>
$ bundle install            <span class="comment"># install gems</span>
...

$ rails db:migrate          <span class="comment"># create and migrate the database</span>
...

$ rails server              <span class="comment"># launch a local server</span>
...

</code></pre>

<p>Go to <code>http://localhost:3000/</code> and you should see something like below.</p>

<!-- Image trigger modal -->
<%= image_tag("rails_success.jpg", class: "img-fluid p-3 shadow", :data => { :target => "#railsSuccessModal", toggle: "modal" }) %>

<!-- Modal -->
<div class="modal fade" id="railsSuccessModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Rails Success Message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag("rails_success.jpg", class: "img-fluid") %>
      </div>
    </div>
  </div>
</div>

</article>

app/views/how_to/partials/_sidenav.html.erb
<!-- Side Navigation Menu -->
<div class="d-none col-sm-12 d-lg-block col-lg-3 bg-white border-right m-0 p-0" style="max-width: 300px">
  <nav class="navbar navbar-expand-lg navbar-light bg-white m-0 p-0">
    <div  class="navbar-collapse flex-column my-3 px-2">
      <h4>Table of Contents</h4>
      <ul class="list-group list-group-flush w-100 f-size-smaller-1">
        <%= link_to 'Rails New', '#rails-new', class: 'list-group-item list-group-item-action w-100 p-2 border-0' %>
        <%= link_to 'Yay!', '#yay', class: 'list-group-item list-group-item-action w-100 p-2 border-0' %>
      </ul>
    </div>
  </nav>
</div>


<!-- Mobile Navigation Menu -->
<div id="mobile-side-nav" class="bg-white border-right py-3 px-2">
  <h4 class="text-center">Table of Contents</h4>
  <ul class="list-group list-group-flush w-100 f-size-smaller-1">
    <%= link_to 'Rails New', '#rails-new', class: 'list-group-item list-group-item-action w-100 p-2 border-0' %>
    <%= link_to 'Yay!', '#yay', class: 'list-group-item list-group-item-action w-100 p-2 border-0' %>
  </ul>
</div>

app/views/how_to/partials/create_a_new_rails_app/_rails_new.html.erb
<!--
  -- This is the Rails New component.
  -- Includes the code and output example.
-->

<article id="rails-new">
  <h3 class="mt-5">Rails New</h3>
  <p class="w-75">Open terminal and navigate to the folder where you want to create the app.</p>

<!-- CODE BLOCK -->
<pre class="bg-dark px-3"><code><span class="badge badge-secondary float-right mt-2">Terminal</span>
$ rails new my_new_app      <span class="comment"># creates an app named 'my_new_app'</span>
...

$ cd my_new_app             <span class="comment"># navigate in to the app folder</span>
$ bundle install            <span class="comment"># install gems</span>
...

$ rails db:migrate          <span class="comment"># create and migrate the database</span>
...

$ rails server              <span class="comment"># launch a local server</span>
...

</code></pre>
<!-- /CODE BLOCK -->

</article>

app/views/how_to/partials/create_a_new_rails_app/_yay_youre_on_rails.html.erb
<!--
  -- This is the Yay! You're On Rails component.
  -- Includes the code and output example.
-->

<article id="yay">
  <h3 class="mt-5">Yay!</h3>
  <p class="w-75">Go to <a href="http://localhost:3000/">http://localhost:3000/</a>. You should see this success message.</p>

    <!-- EXAMPLE -->
    <div class="example p-4">
      <div class="col-12 d-flex justify-content-center">
        <%= image_tag('tutorials/yay_youre_on_rails.png', options = { class: 'img-fluid', alt: "Responsive image"}) %>
      </div>
    </div>
    <!-- /EXAMPLE -->

</article>

app/views/how_to/setup_bootstrap.html.erb
<%= render 'header' %>

<article>
  <h3 class="mt-5">Step 1: Add Bootstrap</h3>
  <p>Go to <code>https://getbootstrap.com/docs/4.4/getting-started/introduction/</code> and get the Bootstrap links.<br><br>
    The simplest way to add Bootstrap is to open <code>app/layouts/application.html.erb</code> and copy/paste the Bootstrap links, like you would with a normal HTML page.</p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">CODE EDITOR</span>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;title&gt;Rails Genius&lt;/title&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"/&gt;
    &lt;%= csrf_meta_tags %&gt;
    &lt;%= csp_meta_tag %&gt;

    &lt;!-- COPY PASTE BOOTSTRAP LINKS HERE --&gt;
    &lt;link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"&gt;
    &lt;script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"&gt;&lt;/script&gt;
    &lt;script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"&gt;&lt;/script&gt;
    &lt;script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"&gt;&lt;/script&gt;
    &lt;!-- END --&gt;

    &lt;%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %&gt;
    &lt;%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %&gt;
  &lt;/head&gt;

  &lt;body&gt;
    &lt;%= yield %&gt;
  &lt;/body&gt;
&lt;/html&gt;

</code></pre>

  <ul>
    <li>This tutorial will get you started quickly. It works. It's not meant to show the most 'optimized' or 'efficient' methods.</li>
    <li>There is another 'Railsy-way' to add Bootstrap that you can find online.</li>
    <li>Some people will say that it is bad practice to add JS in the header.</li>
  </ul>
</article>


<article>
  <h3 class="mt-5">Step 2: Check If It's Working</h3>
  <p>Open your browser and go to <code>http://localhost:3000/</code>.<br>
  You can inspect element or open the JS console to check if it worked.</p>

  <img src="https://miro.medium.com/max/3366/1*CZ7NSJ-eBpwxYVt5OG7ryw.png" class="img-fluid" alt="Responsive image">

</article>

<%= render 'footer' %>

app/views/how_to/skeleton_app.html.erb
<%= render 'layouts/partials/article_header' %>

<article>
  <h3 class="mt-5">Step 1: Generate the App</h3>
  <p>Open terminal and navigate to the folder where you want to create the app.</p>

<pre class="bg-light px-3"><code><span class="badge badge-secondary float-right mt-2">TERMINAL</span>
$ rails new my_first_app
...

$ cd my_first_app
$ bundle install
...

$ rails db:migrate
...

$ rails server
...

</code></pre>

  <ul>
    <li><code>rails new</code> will generate all the files needed to get started.</li>
    <li><code>my_first_app</code> will be the name of the app.</li>
    <li>you will need to navigate into the folder <code>my_first_app</code>.</li>
    <li><code>bundle install</code> will install all the Ruby gems needed to run your application.</li>
    <li><code>rails db:migrate</code> will create the database.</li>
    <li><code>rails server</code> will launch a local server.</li>
  </ul>
</article>


<article>
  <h3 class="mt-5">Step 2: Check If It's Working</h3>
  <p>Open your browser and go to <code>http://localhost:3000/</code>.<br>
  If you see the something like the image below, you've made a basic skeleton Rails app!</p>

  <img src="https://miro.medium.com/max/3366/1*CZ7NSJ-eBpwxYVt5OG7ryw.png" class="img-fluid" alt="Responsive image">

</article>

<%= render 'layouts/partials/article_footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Genius</title>
    <meta charset="UTF-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata&family=Lora:wght@600&family=Nunito:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap 4.4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body onresize="resizeSpy()">
    <%= render 'layouts/partials/nav' %>

    <!-- SideNav Trigger Button -->
    <div class="navbar-dark d-sm-block d-lg-none">
      <button id="trigger-mobile-side-nav" class="navbar-toggler btn-circle bg-danger text-white" type="button" onclick="slideMobileSideNav()">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>

    <div class="container-fluid">
      <div class="row">

        <%= yield %>

      </div>
    </div>

    <script>
      window.onload = function() {
        console.log("window loaded");
        resizeSpy();
      }
    </script>

    <script>
  		function resizeSpy() {
        console.log("init resizeSpy");
        let x = window.innerWidth;

  			if (x < 992) {
          showMobileNav();
  			} else {
          hideMobileNav();
  			}
  		}

      function hideMobileNav() {
        console.log("hiding mobile nav");
        $("#mobile-side-nav").addClass("d-none");
        $("#mobile-side-nav").removeClass("d-block");
      }

      function showMobileNav() {
        console.log("showing mobile nav");
        $("#mobile-side-nav").addClass("d-block");
        $("#mobile-side-nav").removeClass("d-none");
      }
  	</script>

    <script>
      function slideMobileSideNav() {
        console.log("sliding mobile nav");
        $("#mobile-side-nav").toggleClass("show");
      }
    </script>

    <!-- For persistent checkboxes -->
    <script>
      var checkboxValues = JSON.parse(localStorage.getItem('checkboxValues')) || {};
      var $checkboxes = $("#checkbox-container :checkbox");

      // save checkbox values whenever the value changes
      $checkboxes.on("change", function(){
        $checkboxes.each(function(){
          checkboxValues[this.id] = this.checked;
        });
        localStorage.setItem("checkboxValues", JSON.stringify(checkboxValues));
      });

      // iterate over checkbox values and set them when the page loads
      $.each(checkboxValues, function(key, value) {
        $("#" + key).prop('checked', value);
      });
    </script>

  </body>
</html>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
  <a class="navbar-brand" href="#">Rails Genius</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNav" aria-controls="topNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div id="topNav" class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Components
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= active_link_to 'Forms', components_forms_path, class: 'dropdown-item' %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          How To
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= active_link_to 'Create a New Rails App', how_to_create_a_new_rails_app_path, class: 'dropdown-item' %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          App Tutorials
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= active_link_to 'Blog App', tutorials_build_a_blog_app_path, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/partials/_section_main_article_start.html.erb
<section class="main-article col-sm-12 col-lg-9 mx-auto mb-5">